### ISSUE TITLE
[Security] Workflow aspnetcore.yml is using vulnerable action gittools/actions/gitversion/execute

### ISSUE THREAD

**Issue by Ale0x78** [samsmithnz/SamsFeatureFlags#480]
The workflow aspnetcore.yml is referencing action gittools/actions/gitversion/execute using references v0.9.7. However this reference is missing the commit [90150b40fdd6c4b06d39cfd764e900cff45ccfca](https://github.com/gittools/actions/commits/90150b40fdd6c4b06d39cfd764e900cff45ccfca) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by samsmithnz** [comment]
@Ale0x78 - I updated to 0.9.11, 13 days ago, not sure where you are seeing the wrong version? 

https://github.com/samsmithnz/SamsFeatureFlags/blob/229d34572b4f294a3c89cd6c2096ce48e4b41e68/.github/workflows/aspnetcore.yml#L33
