### ISSUE TITLE
Bug: Could not cast or convert from System.String to Azure.ETag.

### ISSUE THREAD

**Issue by samsmithnz** [samsmithnz/SamsFeatureFlags#829]
When running V2.0 against Azure Table Storage:
```
ArgumentException: Could not cast or convert from System.String to Azure.ETag.
Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(object value, Type initialType, Type targetType)

JsonSerializationException: Error converting value "W/"datetime'2023-10-21T05%3A29%3A39.7688543Z'"" to type 'Azure.ETag'. Path '[0].eTag', line 1, position 607.
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, object value, CultureInfo culture, JsonContract contract, Type targetType)
```

**Comment by gioce90** [comment]
I struggled with the same issue. After reading [this pr](https://github.com/Azure/azure-sdk-for-net/pull/16464), it looks like you need the NewtonsoftJsonObjectSerializer (as described [here](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/microsoft.azure.core.newtonsoftjson-readme?view=azure-dotnet)).

So, you need to add this nuget package here:
```
<PackageReference Include="Microsoft.Azure.Core.NewtonsoftJson" Version="2.0.0" />
```

Next, you can choose whether to use the settings within each deserialization operation like this:
```
JsonConvert.DeserializeObject<YourObject>(yourObject, new Azure.Core.Serialization.NewtonsoftJsonETagConverter());
```

Or
```
JsonSerializerSettings serializerSettings = NewtonsoftJsonObjectSerializer.CreateJsonSerializerSettings();
JsonConvert.DeserializeObject<YourObject>(yourObject, serializerSettings);
```
Or simply to apply directly on the property of your interest (I choose this one):
```
[Newtonsoft.Json.JsonConverter(typeof(NewtonsoftJsonETagConverter))]
public ETag ETag { get; set; }
```

**Comment by samsmithnz** [comment]
I did fix this - looks like it was [here](https://github.com/samsmithnz/SamsFeatureFlags/pull/833/files), adding `System.Text.Json.Serialization`. Where are you seeing it broken today?

**Comment by gioce90** [comment]
> I did fix this - just forgot to close the issue - looks like it was [here](https://github.com/samsmithnz/SamsFeatureFlags/pull/833/files), adding `System.Text.Json.Serialization`. Where are you seeing it broken today?

Hi, not in your project but in mine :) I was finding a solution when casually found your issue. 
But in my case the problem was that I don't use `System.Text.Json.Serialization` but only `Newtonsoft.Json`, and in this case I obtained that error.

**Comment by samsmithnz** [comment]
Ahhh - that makes a lot of sense. I remember the docs being a little light when discussing the etag. Glad you found a solution!
